apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxproxyconfig
data: 
  # Need to change this to used FQDNs of mino (as DPS will be requesting the presgined url using its FQDN)
  # <service>.<namespace>.svc.cluster.local:<service_port>
  # AKA minio.default.svc.cluster.local:9000 (although I want to autopopulate the namespace)
  nginx.conf: |
    server {
      listen       80;

      ignore_invalid_headers off;
      client_max_body_size 0;
      proxy_buffering off;
      proxy_request_buffering off;

      location / {
        proxy_set_header Host minio.default.svc.cluster.local:9000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
        proxy_pass http://minio.default.svc.cluster.local:9000;

        }
    }
# Using the dns name rather than the IP address seems to work!

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginxproxy
  name: nginxproxy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginxproxy
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxproxy
  labels:
    app: nginxproxy
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: nginxproxy
  template:
    metadata:
      labels:
        app: nginxproxy
    spec:
      containers:
      - name: nginxproxy
        image: {{ .Values.nginxProxy.image }}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: nginx-config-volume
        configMap: 
          name: nginxproxyconfig
          items:
          - key: nginx.conf
            path: nginx.conf