apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.dataManager.name }}
  name: {{ .Values.dataManager.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.dataManager.name }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dataManager.name }}
  labels:
    app: {{ .Values.dataManager.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dataManager.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dataManager.name }}
    spec:
      containers:
        - name: {{ .Values.dataManager.name }}
          image: {{ .Values.dataManager.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CINCO_DE_BIO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.auth.rootUser }}
            - name: MINIO_SECRET_KEY 
              value: {{ .Values.minio.auth.rootPassword }}
            - name: MINIO_WORKFLOW_BUCKET
              value: {{ .Values.minio.buckets.workflowBucket }}
            - name: MINIO_EXPERIMENT_BUCKET
              value: {{ .Values.minio.buckets.experimentBucket }}
            - name: MINIO_SERVICE_HOSTNAME
              value: {{ .Values.minio.nameOverride }}
            - name: SIB_MANAGER_API_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.sib_manager_ingress_path }}
            - name: EXECUTION_API_INGRESS_PATH
              value: {{ .Values.global.ingress_paths.execution_api_ingress_path }}
            - name: DATA_MANAGER_API_INGRESS
              value: {{ .Values.global.ingress_paths.data_manager_ingress_path }}
            - name: ONTOLOGY_URL
              value: {{ .Values.global.ontology.default_url }}
            - name : DUMMY_VALUE
              value: "dummy"
            - name: CINCO_DE_BIO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            